export interface Country {
  cca3: string;
  name: {
    common: string;
  };
}

export const COUNTRIES: Country[] = [
  { cca3: 'AFG', name: { common: 'Afghanistan' } },
  { cca3: 'ALB', name: { common: 'Albania' } },
  { cca3: 'DZA', name: { common: 'Algeria' } },
  { cca3: 'AND', name: { common: 'Andorra' } },
  { cca3: 'AGO', name: { common: 'Angola' } },
  { cca3: 'ARG', name: { common: 'Argentina' } },
  { cca3: 'ARM', name: { common: 'Armenia' } },
  { cca3: 'AUS', name: { common: 'Australia' } },
  { cca3: 'AUT', name: { common: 'Austria' } },
  { cca3: 'AZE', name: { common: 'Azerbaijan' } },
  { cca3: 'BHS', name: { common: 'Bahamas' } },
  { cca3: 'BHR', name: { common: 'Bahrain' } },
  { cca3: 'BGD', name: { common: 'Bangladesh' } },
  { cca3: 'BRB', name: { common: 'Barbados' } },
  { cca3: 'BLR', name: { common: 'Belarus' } },
  { cca3: 'BEL', name: { common: 'Belgium' } },
  { cca3: 'BLZ', name: { common: 'Belize' } },
  { cca3: 'BEN', name: { common: 'Benin' } },
  { cca3: 'BTN', name: { common: 'Bhutan' } },
  { cca3: 'BOL', name: { common: 'Bolivia' } },
  { cca3: 'BIH', name: { common: 'Bosnia and Herzegovina' } },
  { cca3: 'BWA', name: { common: 'Botswana' } },
  { cca3: 'BRA', name: { common: 'Brazil' } },
  { cca3: 'BRN', name: { common: 'Brunei' } },
  { cca3: 'BGR', name: { common: 'Bulgaria' } },
  { cca3: 'BFA', name: { common: 'Burkina Faso' } },
  { cca3: 'BDI', name: { common: 'Burundi' } },
  { cca3: 'KHM', name: { common: 'Cambodia' } },
  { cca3: 'CMR', name: { common: 'Cameroon' } },
  { cca3: 'CAN', name: { common: 'Canada' } },
  { cca3: 'CPV', name: { common: 'Cape Verde' } },
  { cca3: 'CAF', name: { common: 'Central African Republic' } },
  { cca3: 'TCD', name: { common: 'Chad' } },
  { cca3: 'CHL', name: { common: 'Chile' } },
  { cca3: 'CHN', name: { common: 'China' } },
  { cca3: 'COL', name: { common: 'Colombia' } },
  { cca3: 'COM', name: { common: 'Comoros' } },
  { cca3: 'COG', name: { common: 'Congo' } },
  { cca3: 'COD', name: { common: 'DR Congo' } },
  { cca3: 'CRI', name: { common: 'Costa Rica' } },
  { cca3: 'HRV', name: { common: 'Croatia' } },
  { cca3: 'CUB', name: { common: 'Cuba' } },
  { cca3: 'CYP', name: { common: 'Cyprus' } },
  { cca3: 'CZE', name: { common: 'Czech Republic' } },
  { cca3: 'DNK', name: { common: 'Denmark' } },
  { cca3: 'DJI', name: { common: 'Djibouti' } },
  { cca3: 'DMA', name: { common: 'Dominica' } },
  { cca3: 'DOM', name: { common: 'Dominican Republic' } },
  { cca3: 'ECU', name: { common: 'Ecuador' } },
  { cca3: 'EGY', name: { common: 'Egypt' } },
  { cca3: 'SLV', name: { common: 'El Salvador' } },
  { cca3: 'GNQ', name: { common: 'Equatorial Guinea' } },
  { cca3: 'ERI', name: { common: 'Eritrea' } },
  { cca3: 'EST', name: { common: 'Estonia' } },
  { cca3: 'ETH', name: { common: 'Ethiopia' } },
  { cca3: 'FJI', name: { common: 'Fiji' } },
  { cca3: 'FIN', name: { common: 'Finland' } },
  { cca3: 'FRA', name: { common: 'France' } },
  { cca3: 'GAB', name: { common: 'Gabon' } },
  { cca3: 'GMB', name: { common: 'Gambia' } },
  { cca3: 'GEO', name: { common: 'Georgia' } },
  { cca3: 'DEU', name: { common: 'Germany' } },
  { cca3: 'GHA', name: { common: 'Ghana' } },
  { cca3: 'GRC', name: { common: 'Greece' } },
  { cca3: 'GRD', name: { common: 'Grenada' } },
  { cca3: 'GTM', name: { common: 'Guatemala' } },
  { cca3: 'GIN', name: { common: 'Guinea' } },
  { cca3: 'GNB', name: { common: 'Guinea-Bissau' } },
  { cca3: 'GUY', name: { common: 'Guyana' } },
  { cca3: 'HTI', name: { common: 'Haiti' } },
  { cca3: 'HND', name: { common: 'Honduras' } },
  { cca3: 'HUN', name: { common: 'Hungary' } },
  { cca3: 'ISL', name: { common: 'Iceland' } },
  { cca3: 'IND', name: { common: 'India' } },
  { cca3: 'IDN', name: { common: 'Indonesia' } },
  { cca3: 'IRN', name: { common: 'Iran' } },
  { cca3: 'IRQ', name: { common: 'Iraq' } },
  { cca3: 'IRL', name: { common: 'Ireland' } },
  { cca3: 'ISR', name: { common: 'Israel' } },
  { cca3: 'ITA', name: { common: 'Italy' } },
  { cca3: 'JAM', name: { common: 'Jamaica' } },
  { cca3: 'JPN', name: { common: 'Japan' } },
  { cca3: 'JOR', name: { common: 'Jordan' } },
  { cca3: 'KAZ', name: { common: 'Kazakhstan' } },
  { cca3: 'KEN', name: { common: 'Kenya' } },
  { cca3: 'KIR', name: { common: 'Kiribati' } },
  { cca3: 'PRK', name: { common: 'North Korea' } },
  { cca3: 'KOR', name: { common: 'South Korea' } },
  { cca3: 'KWT', name: { common: 'Kuwait' } },
  { cca3: 'KGZ', name: { common: 'Kyrgyzstan' } },
  { cca3: 'LAO', name: { common: 'Laos' } },
  { cca3: 'LVA', name: { common: 'Latvia' } },
  { cca3: 'LBN', name: { common: 'Lebanon' } },
  { cca3: 'LSO', name: { common: 'Lesotho' } },
  { cca3: 'LBR', name: { common: 'Liberia' } },
  { cca3: 'LBY', name: { common: 'Libya' } },
  { cca3: 'LIE', name: { common: 'Liechtenstein' } },
  { cca3: 'LTU', name: { common: 'Lithuania' } },
  { cca3: 'LUX', name: { common: 'Luxembourg' } },
  { cca3: 'MKD', name: { common: 'North Macedonia' } },
  { cca3: 'MDG', name: { common: 'Madagascar' } },
  { cca3: 'MWI', name: { common: 'Malawi' } },
  { cca3: 'MYS', name: { common: 'Malaysia' } },
  { cca3: 'MDV', name: { common: 'Maldives' } },
  { cca3: 'MLI', name: { common: 'Mali' } },
  { cca3: 'MLT', name: { common: 'Malta' } },
  { cca3: 'MHL', name: { common: 'Marshall Islands' } },
  { cca3: 'MRT', name: { common: 'Mauritania' } },
  { cca3: 'MUS', name: { common: 'Mauritius' } },
  { cca3: 'MEX', name: { common: 'Mexico' } },
  { cca3: 'FSM', name: { common: 'Micronesia' } },
  { cca3: 'MDA', name: { common: 'Moldova' } },
  { cca3: 'MCO', name: { common: 'Monaco' } },
  { cca3: 'MNG', name: { common: 'Mongolia' } },
  { cca3: 'MNE', name: { common: 'Montenegro' } },
  { cca3: 'MAR', name: { common: 'Morocco' } },
  { cca3: 'MOZ', name: { common: 'Mozambique' } },
  { cca3: 'MMR', name: { common: 'Myanmar' } },
  { cca3: 'NAM', name: { common: 'Namibia' } },
  { cca3: 'NRU', name: { common: 'Nauru' } },
  { cca3: 'NPL', name: { common: 'Nepal' } },
  { cca3: 'NLD', name: { common: 'Netherlands' } },
  { cca3: 'NZL', name: { common: 'New Zealand' } },
  { cca3: 'NIC', name: { common: 'Nicaragua' } },
  { cca3: 'NER', name: { common: 'Niger' } },
  { cca3: 'NGA', name: { common: 'Nigeria' } },
  { cca3: 'NOR', name: { common: 'Norway' } },
  { cca3: 'OMN', name: { common: 'Oman' } },
  { cca3: 'PAK', name: { common: 'Pakistan' } },
  { cca3: 'PLW', name: { common: 'Palau' } },
  { cca3: 'PAN', name: { common: 'Panama' } },
  { cca3: 'PNG', name: { common: 'Papua New Guinea' } },
  { cca3: 'PRY', name: { common: 'Paraguay' } },
  { cca3: 'PER', name: { common: 'Peru' } },
  { cca3: 'PHL', name: { common: 'Philippines' } },
  { cca3: 'POL', name: { common: 'Poland' } },
  { cca3: 'PRT', name: { common: 'Portugal' } },
  { cca3: 'QAT', name: { common: 'Qatar' } },
  { cca3: 'ROU', name: { common: 'Romania' } },
  { cca3: 'RUS', name: { common: 'Russia' } },
  { cca3: 'RWA', name: { common: 'Rwanda' } },
  { cca3: 'KNA', name: { common: 'Saint Kitts and Nevis' } },
  { cca3: 'LCA', name: { common: 'Saint Lucia' } },
  { cca3: 'VCT', name: { common: 'Saint Vincent and the Grenadines' } },
  { cca3: 'WSM', name: { common: 'Samoa' } },
  { cca3: 'SMR', name: { common: 'San Marino' } },
  { cca3: 'STP', name: { common: 'Sao Tome and Principe' } },
  { cca3: 'SAU', name: { common: 'Saudi Arabia' } },
  { cca3: 'SEN', name: { common: 'Senegal' } },
  { cca3: 'SRB', name: { common: 'Serbia' } },
  { cca3: 'SYC', name: { common: 'Seychelles' } },
  { cca3: 'SLE', name: { common: 'Sierra Leone' } },
  { cca3: 'SGP', name: { common: 'Singapore' } },
  { cca3: 'SVK', name: { common: 'Slovakia' } },
  { cca3: 'SVN', name: { common: 'Slovenia' } },
  { cca3: 'SLB', name: { common: 'Solomon Islands' } },
  { cca3: 'SOM', name: { common: 'Somalia' } },
  { cca3: 'ZAF', name: { common: 'South Africa' } },
  { cca3: 'SSD', name: { common: 'South Sudan' } },
  { cca3: 'ESP', name: { common: 'Spain' } },
  { cca3: 'LKA', name: { common: 'Sri Lanka' } },
  { cca3: 'SDN', name: { common: 'Sudan' } },
  { cca3: 'SUR', name: { common: 'Suriname' } },
  { cca3: 'SWE', name: { common: 'Sweden' } },
  { cca3: 'CHE', name: { common: 'Switzerland' } },
  { cca3: 'SYR', name: { common: 'Syria' } },
  { cca3: 'TWN', name: { common: 'Taiwan' } },
  { cca3: 'TJK', name: { common: 'Tajikistan' } },
  { cca3: 'TZA', name: { common: 'Tanzania' } },
  { cca3: 'THA', name: { common: 'Thailand' } },
  { cca3: 'TLS', name: { common: 'Timor-Leste' } },
  { cca3: 'TGO', name: { common: 'Togo' } },
  { cca3: 'TON', name: { common: 'Tonga' } },
  { cca3: 'TTO', name: { common: 'Trinidad and Tobago' } },
  { cca3: 'TUN', name: { common: 'Tunisia' } },
  { cca3: 'TUR', name: { common: 'Turkey' } },
  { cca3: 'TKM', name: { common: 'Turkmenistan' } },
  { cca3: 'TUV', name: { common: 'Tuvalu' } },
  { cca3: 'UGA', name: { common: 'Uganda' } },
  { cca3: 'UKR', name: { common: 'Ukraine' } },
  { cca3: 'ARE', name: { common: 'United Arab Emirates' } },
  { cca3: 'GBR', name: { common: 'United Kingdom' } },
  { cca3: 'USA', name: { common: 'United States' } },
  { cca3: 'URY', name: { common: 'Uruguay' } },
  { cca3: 'UZB', name: { common: 'Uzbekistan' } },
  { cca3: 'VUT', name: { common: 'Vanuatu' } },
  { cca3: 'VAT', name: { common: 'Vatican City' } },
  { cca3: 'VEN', name: { common: 'Venezuela' } },
  { cca3: 'VNM', name: { common: 'Vietnam' } },
  { cca3: 'YEM', name: { common: 'Yemen' } },
  { cca3: 'ZMB', name: { common: 'Zambia' } },
  { cca3: 'ZWE', name: { common: 'Zimbabwe' } }
];
